import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { name, email, experience, education, skills } = await req.json();

    const cvText = `
    CV Generated by MilkBox AI
    ==========================

    Name: ${name}
    Email: ${email}

    Experience:
    ${experience}

    Education:
    ${education}

    Skills:
    ${skills}
    `;

    return NextResponse.json({ ok: true, cv: cvText });
  } catch (err) {
    console.error("CV route error:", err);
    return NextResponse.json(
      { ok: false, error: "Failed to generate CV" },
      { status: 500 }
    );
  }
}
